spring.profiles.active=test

##Essa config permite que os "jackson" na hora de serializar o JSON, identifique a lista
##dentro da entidade principal, por exemplo em USER, vai mostrar a lista de
## pedidos que foram realizados pela pessoa
spring.jpa.open-in-view=true